name: Fetch SFMC Asset JSON

on:
  workflow_dispatch:

jobs:
  fetch-html-metadata:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Ensure output folder exists
        run: mkdir -p content

      - name: Install dependencies
        run: npm install axios

      - name: Fetch SFMC asset JSON response
        run: node scripts/fetchSfmcHtml.js
        env:
          SFMC_CLIENT_ID: ${{ secrets.SFMC_CLIENT_ID }}
          SFMC_CLIENT_SECRET: ${{ secrets.SFMC_CLIENT_SECRET }}
          SFMC_ACCOUNT_ID: ${{ secrets.SFMC_ACCOUNT_ID }}
          SFMC_AUTH_BASE_URL: ${{ secrets.SFMC_AUTH_BASE_URL }}
          SFMC_REST_BASE_URL: ${{ secrets.SFMC_REST_BASE_URL }}
          SFMC_ASSET_KEY: ${{ secrets.SFMC_ASSET_KEY }}

      - name: Commit and push response JSON
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git pull origin main --rebase
          git add content/
          git commit -m "Update SFMC HTML content" || echo "No changes to commit"
          git push origin main
        continue-on-error: true
