name: Fetch SFMC HTML

on:
  workflow_dispatch:

jobs:
  fetch-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install axios

      - name: Fetch asset JSON from SFMC
        run: node scripts/fetchAsset.js
        env:
          SFMC_CLIENT_ID: ${{ secrets.SFMC_CLIENT_ID }}
          SFMC_CLIENT_SECRET: ${{ secrets.SFMC_CLIENT_SECRET }}
          SFMC_ACCOUNT_ID: ${{ secrets.SFMC_ACCOUNT_ID }}
          SFMC_AUTH_BASE_URL: ${{ secrets.SFMC_AUTH_BASE_URL }}
          SFMC_REST_BASE_URL: ${{ secrets.SFMC_REST_BASE_URL }}
          SFMC_ASSET_KEY: ${{ secrets.SFMC_ASSET_KEY }}

      - name: Upload raw response as artifact
        uses: actions/upload-artifact@v4
        with:
          name: sfmc-response
          path: content/*_response.json

      - name: Extract HTML from JSON
        run: node scripts/extractHtml.js
        env:
          SFMC_ASSET_KEY: ${{ secrets.SFMC_ASSET_KEY }}

      - name: Commit and push HTML
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add content/*.html
          git commit -m "Update SFMC HTML content" || echo "No changes to commit"
          git push
